##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - aptitude
    - autoconf-archive
    - debhelper
    - dh-python
    - dpkg-dev
    - git
    - python3
    - python3-gi
    - python3-polib
    - python3-setuptools

    #required packages for baul
    - gla11y
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgirepository1.0-dev
    - libglib2.0-doc
    - libnotify-dev
    - libpango1.0-dev
    - libselinux1-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxml2-dev
    - meson
    - python3-lxml
    - quilt
    - shared-mime-info
    - xvfb

before_scripts:
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 ctk-update-icon-cache libcail-3-0 libcail-3-dev'
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master
  - ./install-from-git https://github.com/cafe-desktop/baul master

build_scripts:
  - mkdir html-report
  - python3 setup.py build
  - python3 setup.py install --root=/ --optimize=1
  - dpkg-buildpackage -b -rfakeroot -us -uc
  - cd ..
  - dpkg -i *.deb
