##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - expect #required for unbuffer
    - python3
    - python3-polib
    - python3-setuptools

build_scripts:
  - ./debrepo-install
  - ./build-debs
