##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - expect #required for unbuffer
    - python3
    - python3-pip
    - python3-polib
    - python3-setuptools

build_scripts:
  - mkdir html-report
  - unbuffer python3 setup.py build | tee -a --output-error=exit ./html-report/output_${TRAVIS_COMMIT}
  - if [ ${PIPESTATUS[0]} -ne 0 ];then
      exit 1
  - fi
  - unbuffer python3 setup.py install --root=/ --optimize=1 | tee -a --output-error=exit ./html-report/output_${TRAVIS_COMMIT}
  - if [ ${PIPESTATUS[0]} -ne 0 ];then
  -   exit 1
  - fi
