##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - expect #required for unbuffer
    - python3
    - python3-polib
    - python3-setuptools

build_scripts:
  - git clone --depth 1 https://github.com/cafe-desktop/debian-packages -b gh-pages tmp-install
  - cd tmp-install
  - dpkg -i *.deb
#  - ./debrepo-install.sh
#  - ./build-debs
