##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - expect #required for unbuffer
    - pipx
    - python3
    - python3-pip
    - python3-polib
    - python3-setuptools

build_scripts:
  - pipx install build
  - mkdir html-report
  - unbuffer python3 -m build | tee -a --output-error=exit ./html-report/output_${TRAVIS_COMMIT}
  - if [ ${PIPESTATUS[0]} -ne 0 ];then
      exit 1
  - fi
  - unbuffer python3 -m pip install . --prefix=/ --optimize | tee -a --output-error=exit ./html-report/output_${TRAVIS_COMMIT}
  - if [ ${PIPESTATUS[0]} -ne 0 ];then
  -   exit 1
  - fi
