##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - debhelper
    - dh-python
    - dpkg-dev
    - python3
    - python3-gi
    - python3-polib
    - python3-setuptools

before_scripts:
  - ./debrepo-install 'gir1.2-ctk-3.0'

build_scripts:
  - mkdir html-report
  - python3 setup.py build
  - python3 setup.py install --root=/ --optimize=1
  - dpkg-buildpackage -b -rfakeroot -us -uc
  - cd ..
  - dpkg -i *.deb
